apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-b
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker-b
  template:
    metadata:
      labels:
        component: spark-worker-b
    spec:
      containers:
        - name: spark-worker-b
          image: dperdices/spark-worker:latest
          env:
            - name: SPARK_MASTER-B
              value: spark://spark-master-b:7077
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
