apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-b
  labels:
    app: spark
    role: master
    cluster: b
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master-b
  template:
    metadata:
      labels:
        component: spark-master-b
        cluster: b
    spec:
      containers:
        - name: spark-master-b
          image: dperdices/spark-master:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_MASTER_HOST
              value: spark-master-b               # <- nombre del Service B
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"