apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-a
  labels:
    app: spark
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master-a
  template:
    metadata:
      labels:
        component: spark-master-a
    spec:
      containers:
        - name: spark-master
          image: dperdices/spark-master:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_HOST
              value: spark-master-a
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"